### ISSUE TITLE
Add forms events in to triggers

### ISSUE THREAD

**Issue by radiansz** [sendsay-ru/account#117]
In current implementation of triggers there are no events for handling forms. There is old branch(https://github.com/sendsay-ru/account/tree/trigger_forms) where this modifications have been made but it was forked form master instead of forms. 
Need to transfer those modifications in to new branch forked from forms.

**Comment by rosendi** [comment]
Closed https://github.com/sendsay-ru/account/commit/3aaf05b7868b330bbd736a88514fffed67b7e01c
