### ISSUE TITLE
Triggering "Help" drop down menu closes FAB. 

### ISSUE THREAD

**Issue by trikashny** [sendsay-ru/account#148]
But this menu doesn't overlap FAB, so there is no need to hide FAB.

Seems, that this this issue came up from this PR [https://github.com/sendsay-ru/account/pull/130](url)

**Comment by rosendi** [comment]
Merged here https://github.com/sendsay-ru/account/commit/6dc7ec97b570947c0f06e47f0f0b8cb95e6d5cd7
