### ISSUE TITLE
Long template name breaks the grid

### ISSUE THREAD

**Issue by trikashny** [sendsay-ru/account#170]
We use "long names cut" method in other parts of system, and we should apply it here. If template name is longer than 2 rows it must be cutted with "…"

![image](https://cloud.githubusercontent.com/assets/6356996/17871148/01888c94-68c3-11e6-9377-8d9e4c8dc517.png)

**Comment by rosendi** [comment]
Fixed https://github.com/sendsay-ru/account/commit/f52ae0fb5ebf655f1529c54681e8e6ec85e7db17
