### ISSUE TITLE
Form type radio styles change

### ISSUE THREAD

**Issue by trikashny** [sendsay-ru/account#218]
1. Align radio vertically with step index circle http://snpy.in/tqUX5h.
2. Change fill color of `.radioButton input:not(:checked) ~ .radioButton__content .radioButton__iconContent .icon path ` to `fill: #5F6871;`
3. Add hover classes for radio
```
.radioButton input:not(:checked) ~ .radioButton__content:hover .radioButton__iconContent .icon path:first-child {
    opacity: .4;
}    
```
and
```
.radioButton input:not(:checked) ~ .radioButton__content:hover .radioButton__iconContent .icon path {
    opacity: .8;
}
```

**Comment by rosendi** [comment]
https://github.com/sendsay-ru/account/commit/711e44c95e9973c30404b4721a5ca91bc7057815
