### ISSUE TITLE
Get rid of duplicated code for generating email preview in to iframe.

### ISSUE THREAD

**Issue by radiansz** [sendsay-ru/account#82]
Many of those in wizard. Special logic in clickmap, special logic in draftPreview.
Links to duplicate parts:
1) https://github.com/sendsay-ru/account/blob/forms/src/blocks/wizard/__info/templateEditContent/templateEditContent.js
2) https://github.com/sendsay-ru/account/blob/forms/src/blocks/wizard/__info/formEditConfirmLetter/formEditConfirmLetter.js
3) https://github.com/sendsay-ru/account/blob/forms/src/blocks/wizard/__info/draftEditContent/draftEditContent.js)
Links to similar but not exact cases:
1) https://github.com/sendsay-ru/account/blob/forms/src/blocks/clickmap/clickmap.js#L108
2) https://github.com/sendsay-ru/account/blob/forms/src/blocks/draftPreview/draftPreview.js#L42

**Comment by rosendi** [comment]
Could you please provide more info? A link to the source code would be helpful.

**Comment by Radiansz** [comment]
Main description has been updated
