### ISSUE TITLE
Not drag blocks of content in a wizard

### ISSUE THREAD

**Issue by devmaster-st** [sendsay-ru/account#92]
I'm trying to drag'n'drop text block in wizard form (http://localhost:8080/mailings/wizard?mode=create), but  when released it does not appear to form.

Because of this tests aren't performed.

[http://joxi.ru/GrqKXx7iK5oZ2z](url)

**Comment by rosendi** [comment]
The ling you provided is broken.

**Comment by rosendi** [comment]
closed https://github.com/sendsay-ru/account/pull/114
